version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    groups:
      go:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
